name: lupine_sdk
description: Secure, encrypted cloud drive service built on Nostr protocol with real-time sync.
version: 2.0.0
repository: https://github.com/nogringo/lupine-sdk

environment:
  sdk: ^3.8.1

dependencies:
  bech32: ^0.2.2
  convert: ^3.1.2
  crypto: ^3.0.6
  cryptography: ^2.7.0
  ndk: ^0.5.0
  nip01: ^0.3.0+1
  nip19: ^0.2.0
  nip49: ^1.1.1
  path: ^1.9.1
  pointycastle: ^3.9.1
  sembast: ^3.8.5+1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
