name: lupine_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  convert: ^3.1.2
  crypto: ^3.0.6
  cryptography: ^2.7.0
  ndk: ^0.5.0
  nip01: ^0.3.0+1
  nip19: ^0.2.0
  path: ^1.9.1
  pointycastle: ^3.9.1
  sembast: ^3.8.5+1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
